all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
    proxmox_nodes:
      hosts:
        pve:
          ansible_host: 192.168.5.2
          ansible_user: root
          ansible_ssh_pass: "{{ vault_proxmox_root_password }}"
          ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    goldimage:
      hosts:
        goldimage_vm:
          ansible_host: 192.168.5.172
          ansible_user: Admin
          ansible_password: "{{ vault_goldimage_password }}"
          ansible_connection: winrm
          ansible_port: 5985
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
    winpe_builder:
      hosts:
        winserv2025:
          ansible_host: 192.168.5.171
          ansible_user: Administrator
          ansible_password: "{{ vault_winpe_builder_password }}"
          ansible_connection: winrm
          ansible_port: 5985
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
    deployer_lxc:
      hosts:
        win-deploy-lxc:
          ansible_host: 192.168.5.2
          ansible_user: root
          ansible_password: "{{ vault_proxmox_root_password }}"
          ansible_connection: community.proxmox.proxmox_pct_remote
          proxmox_vmid: 131
