connector.name=iceberg
iceberg.catalog.type=nessie
iceberg.nessie-catalog.uri=http://nessie:19120/api/v2
iceberg.nessie-catalog.ref=main
iceberg.nessie-catalog.default-warehouse-dir=/data/iceberg/warehouse
fs.hadoop.enabled=true
iceberg.file-format=PARQUET
iceberg.compression-codec=ZSTD
