---
- name: Restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted

- name: Restart dnsmasq
  ansible.builtin.systemd_service:
    name: dnsmasq
    state: restarted

- name: Restart smbd
  ansible.builtin.systemd_service:
    name: smbd
    state: restarted
