---
- ansible.builtin.import_tasks: packages.yml
- ansible.builtin.import_tasks: filesystem.yml
- ansible.builtin.import_tasks: nginx.yml
- ansible.builtin.import_tasks: samba.yml
- ansible.builtin.import_tasks: dnsmasq.yml
- ansible.builtin.import_tasks: ipxe.yml
- ansible.builtin.import_tasks: offline_tui.yml
- meta: flush_handlers
- ansible.builtin.import_tasks: validation.yml
